apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 384504715772.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 384504715772.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: 54f1c2bb
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
